apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cequence

commonLabels:
  app.kubernetes.io/part-of: cequence-blackwall

resources:
  - namespace.yaml
  - blackwall-deployment.yaml
  - blackwall-service.yaml
